//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHI
    {
        public int IDPhi { get; set; }
        public Nullable<int> IDDonHang { get; set; }
        public string Gia { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
